service: eventbrite-alexa-skill

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

functions:
  handler:
    handler: handler.handler
    events:
      - alexaSkill: ${ssm:eventbriteSkillID}
